/**
 * 工具基底類別
 *
 * 支援兩種使用模式：
 * 1. 普通模式：工具作為單一實體使用
 * 2. 可展開模式：工具可以展開為多個獨立的子工具（每個子工具對應一個功能）
 *
 * 展開模式支援兩種實作方式：
 * - 手動定義子工具類別（傳統方式）
 * - 使用 toolAction 裝飾器標記自動生成（推薦）
 */

/**
 * 裝飾器：標記一個方法為可展開的工具 action
 *
 * 用法：
 *   class MyTool extends Tool {
 *     constructor() { super('my_tool', '我的工具', { expandable: true }); }
 *     myAction(content, importance = 0.5) { ... }
 *   }
 *   toolAction('memory_add', '新增記憶')(MyTool.prototype, 'myAction');
 *
 * @param {string|null} name - 工具名稱（未提供則從方法名自動生成）
 * @param {string|null} description - 工具描述（未提供則使用方法名）
 * @returns {Function} 裝飾器函式
 */
export function toolAction(name = null, description = null) {
  return function (target, propertyKey) {
    const method = target[propertyKey];
    if (typeof method !== 'function') return;
    method._isToolAction = true;
    method._toolName = name;
    method._toolDescription = description;
  };
}

/**
 * 工具參數定義
 */
export class ToolParameter {
  /**
   * @param {Object} opts
   * @param {string} opts.name - 參數名稱
   * @param {string} opts.type - 參數類型（string / integer / number / boolean / array / object）
   * @param {string} opts.description - 參數描述
   * @param {boolean} opts.required - 是否必填
   * @param {*} opts.default - 預設值
   */
  constructor({ name, type, description, required = true, default: defaultVal = null }) {
    this.name = name;
    this.type = type;
    this.description = description;
    this.required = required;
    this.default = defaultVal;
  }
}

/**
 * 工具基底類別（抽象）
 *
 * 子類別必須實作 run() 和 getParameters()。
 */
export class Tool {
  /**
   * 初始化工具
   * @param {string} name - 工具名稱
   * @param {string} description - 工具描述
   * @param {Object} opts
   * @param {boolean} opts.expandable - 是否可展開為多個子工具
   */
  constructor(name, description, { expandable = false } = {}) {
    if (new.target === Tool) {
      throw new Error('Tool 是抽象類別，不能直接實例化');
    }
    this.name = name;
    this.description = description;
    this.expandable = expandable;
  }

  /**
   * 執行工具（子類別必須實作）
   * @param {Object} parameters - 參數字典
   * @returns {string} 執行結果
   */
  run(parameters) {
    throw new Error('run() 必須由子類別實作');
  }

  /**
   * 獲取工具參數定義（子類別必須實作）
   * @returns {ToolParameter[]}
   */
  getParameters() {
    throw new Error('getParameters() 必須由子類別實作');
  }

  /**
   * 獲取展開後的子工具列表
   *
   * 預設實作：自動從標記了 toolAction 的方法生成子工具。
   * 子類別可以覆寫此方法提供自訂的展開邏輯。
   *
   * @returns {Tool[]|null} 如果工具支援展開，回傳子工具列表；否則回傳 null
   */
  getExpandedTools() {
    if (!this.expandable) return null;

    // 自動從裝飾器標記的方法生成工具
    const tools = [];
    const proto = Object.getPrototypeOf(this);
    const methodNames = Object.getOwnPropertyNames(proto).filter(
      n => n !== 'constructor' && typeof proto[n] === 'function'
    );

    for (const methodName of methodNames) {
      const method = proto[methodName];
      if (method._isToolAction) {
        const tool = new AutoGeneratedTool({
          parent: this,
          method: method.bind(this),
          name: method._toolName,
          description: method._toolDescription,
        });
        tools.push(tool);
      }
    }

    return tools.length ? tools : null;
  }

  /**
   * 驗證參數
   * @param {Object} parameters - 參數字典
   * @returns {boolean}
   */
  validateParameters(parameters) {
    const requiredParams = this.getParameters().filter(p => p.required).map(p => p.name);
    return requiredParams.every(param => param in parameters);
  }

  /**
   * 轉換為字典格式
   * @returns {Object}
   */
  toDict() {
    return {
      name: this.name,
      description: this.description,
      parameters: this.getParameters().map(p => ({ ...p })),
    };
  }

  /**
   * 轉換為 OpenAI function calling schema 格式
   *
   * 用於 FunctionCallAgent，使工具能夠被 OpenAI 原生 function calling 使用。
   *
   * @returns {Object} 符合 OpenAI function calling 標準的 schema
   */
  toOpenAISchema() {
    const parameters = this.getParameters();
    const properties = {};
    const required = [];

    for (const param of parameters) {
      const prop = {
        type: param.type,
        description: param.description,
      };

      // 如果有預設值，添加到描述中（OpenAI schema 不支援 default 欄位）
      if (param.default != null) {
        prop.description = `${param.description}（預設: ${param.default}）`;
      }

      // 如果是陣列類型，添加 items 定義
      if (param.type === 'array') {
        prop.items = { type: 'string' };
      }

      properties[param.name] = prop;

      if (param.required) required.push(param.name);
    }

    return {
      type: 'function',
      function: {
        name: this.name,
        description: this.description,
        parameters: { type: 'object', properties, required },
      },
    };
  }

  toString() {
    return `Tool(name=${this.name})`;
  }
}

/**
 * 自動生成的工具 — 從方法簽名自動提取參數
 */
export class AutoGeneratedTool extends Tool {
  /**
   * @param {Object} opts
   * @param {Tool} opts.parent - 父工具實例
   * @param {Function} opts.method - 被裝飾的方法
   * @param {string|null} opts.name - 工具名稱（null 則從方法名生成）
   * @param {string|null} opts.description - 工具描述（null 則使用方法名）
   */
  constructor({ parent, method, name = null, description = null }) {
    // 生成工具名稱
    if (name == null) {
      const methodName = (method._toolName || method.name || 'action').replace(/^_+/, '');
      name = `${parent.name}_${methodName}`;
    }

    // 提取描述
    if (description == null) {
      description = method._toolDescription || `執行 ${method.name || 'action'}`;
    }

    // 呼叫 Tool 時需要避免抽象類別檢查
    // AutoGeneratedTool 本身不是 Tool，所以 new.target 不會是 Tool
    super(name, description);

    this.parent = parent;
    this.method = method;
    this._parameters = [];
  }

  /**
   * 獲取參數列表
   * @returns {ToolParameter[]}
   */
  getParameters() {
    return this._parameters;
  }

  /**
   * 執行方法
   * @param {Object} parameters
   * @returns {string}
   */
  run(parameters) {
    return this.method(parameters);
  }
}
